# Generated by Django 4.0.4 on 2022-04-21 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_registration_trainer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Achievement_title', models.CharField(blank=True, max_length=100, null=True)),
                ('Achievement_description', models.TextField(blank=True, null=True)),
                ('Achievement_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=100)),
                ('fromtime', models.TimeField(blank=True, null=True)),
                ('totime', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee', models.CharField(max_length=100)),
                ('payacnt', models.CharField(max_length=100)),
                ('paymethod', models.CharField(max_length=100)),
                ('paydate', models.CharField(max_length=100)),
                ('refno', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('tax', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=50)),
                ('machine_details', models.CharField(max_length=200)),
                ('machine_image', models.ImageField(null=True, upload_to='images/')),
                ('machine_description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=225)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='user_registration',
            name='rate',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='images/')),
                ('Workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='app.workout')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('payment', models.CharField(max_length=240, null=True)),
                ('bank', models.CharField(max_length=240, null=True)),
                ('accountnumber', models.CharField(max_length=240, null=True)),
                ('ifse', models.CharField(max_length=240, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.user_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=200)),
                ('cate_details', models.CharField(max_length=200)),
                ('cate_image', models.ImageField(null=True, upload_to='images/')),
                ('cate_description', models.TextField(max_length=200)),
                ('cate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machinenames', to='app.machine')),
            ],
        ),
    ]
